const canvas = document.getElementById("overlay");

export const dom = {
  video: document.getElementById("video"),
  canvas,
  ctx: canvas ? canvas.getContext("2d") : null,
  statusEl: document.getElementById("status"),
  stepTitle: document.getElementById("step-title"),
  stepBody: document.getElementById("step-body"),
  stepHint: document.getElementById("step-hint"),
  stepCounter: document.getElementById("step-counter"),
  progressBar: document.getElementById("progress-bar"),
  gestureLabel: document.getElementById("gesture-label"),
  gestureConfidence: document.getElementById("gesture-confidence"),
  gestureFps: document.getElementById("gesture-fps"),
  thresholdInput: document.getElementById("threshold"),
  thresholdValue: document.getElementById("threshold-value"),
  thresholdLabel: document.getElementById("threshold-label"),
  gestureScoreEl: document.getElementById("gesture-score"),
  gestureStatusEl: document.getElementById("gesture-status"),
  bestThresholdEl: document.getElementById("best-threshold"),
  badgeStateEl: document.getElementById("badge-state"),
  statLabelScore: document.getElementById("stat-label-score"),
  statLabelStatus: document.getElementById("stat-label-status"),
  statLabelBest: document.getElementById("stat-label-best"),
  statLabelBadge: document.getElementById("stat-label-badge"),
  scoreTotalEl: document.getElementById("score-total"),
  missionActiveEl: document.getElementById("mission-active"),
  challengePanel: document.getElementById("challenge-panel"),
  badgeChips: Array.from(document.querySelectorAll(".badge-chip")),
  heroTitle: document.getElementById("hero-title"),
  heroBody: document.getElementById("hero-body"),
  stageTitle: document.getElementById("stage-title"),
  stageDesc: document.getElementById("stage-desc"),
  missionTitle: document.getElementById("mission-title"),
  missionSubtitle: document.getElementById("mission-subtitle"),
  stageMedia: document.getElementById("stage-media"),
  stagePlaceholder: document.getElementById("stage-placeholder"),
  kpiLabelGesture: document.getElementById("kpi-label-gesture"),
  kpiLabelConfidence: document.getElementById("kpi-label-confidence"),
  kpiLabelFps: document.getElementById("kpi-label-fps"),
  navHome: document.getElementById("nav-home"),
  navPrev: document.getElementById("nav-prev"),
  navNext: document.getElementById("nav-next"),
  missionCards: document.getElementById("mission-cards"),
  inferenceTimeEl: document.getElementById("inference-time"),
  gestureBarName: document.getElementById("gesture-bar-name"),
  gestureBarScore: document.getElementById("gesture-bar-score"),
  gestureBarFill: document.getElementById("gesture-bar-fill"),
  gestureReadout: document.getElementById("gesture-readout"),
  gestureControls: document.getElementById("gesture-controls"),
  delegateSelect: document.getElementById("delegate-select"),
  modelSelect: document.getElementById("model-select"),
  numHandsInput: document.getElementById("num-hands"),
  numHandsValue: document.getElementById("num-hands-value"),
  minDetectionInput: document.getElementById("min-detection"),
  minDetectionValue: document.getElementById("min-detection-value"),
  minPresenceInput: document.getElementById("min-presence"),
  minPresenceValue: document.getElementById("min-presence-value"),
  minTrackingInput: document.getElementById("min-tracking"),
  minTrackingValue: document.getElementById("min-tracking-value"),
  configWarningEl: document.getElementById("config-warning")
};
